import {Inter} from "next/font/google";
import type {Metadata} from "next";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin", "cyrillic"],
    display: "swap",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
interface Props {children: React.ReactNode}

export default function RootLayout({children}: Props) {

    return (
        <html>
            <body className={`${inter.className} ${inter.variable} antialiased`}>
                {children}
            </body>
        </html>
    )
}