import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Header} from "@/shared/components/Header";
import {Footer} from "@/shared/components/Footer";
import {routing} from "@/shared/lib/i18n/routing";
const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin", "cyrillic"],
    display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang={routing.defaultLocale}>
          <body
            className={`${inter.className} ${inter.variable} antialiased`}
          >
                <Header />
                    {children}
                <Footer />
          </body>
      </html>
  );
}
