import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "../../globals.css";
import {Header} from "@/shared/components/Header";
import {Footer} from "@/shared/components/Footer";
import {hasLocale} from "use-intl";
import {routing} from "@/shared/lib/i18n/routing";
import {notFound} from "next/navigation";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin", "cyrillic"],
    display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}

export default async function PublicLayout(
    { children, params }: Props,
) {
    const { locale } = await params;

    if (!hasLocale(routing.locales, locale)) notFound();
    const messages = await getMessages();



  return (
      <html lang={locale}>
          <body
            className={`${inter.className} ${inter.variable} antialiased`}
          >
          <NextIntlClientProvider locale={locale} messages={messages}>
              <Header />
                    {children}
              <Footer />
          </NextIntlClientProvider>
          </body>
      </html>
  );
}


export async function generateStaticParams() {
    return routing.locales.map((locale) => ({
        locale: locale
    }));
}